<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Meta Title' => 'Meta virsraksts',
    'Reference' => 'Sasaistes atslēgas',
    'Version' => 'Versija',
    'View' => 'Skats',
    '(no parent)' => '(nav vecāka)',
    'Actions' => 'Darbības',
    'Add' => 'Pievienot',
    'Add new Category' => 'Pievienot jaunu kategoriju',
    'Add new Post' => 'Pievienot jaunu rakstu',
    'An error has occurred ({error})' => 'Kļūda ({error})',
    'Are you sure you want to delete this record?' => 'Vai jūs tiešām gribat dzēst šo ierakstu?',
    'Author' => 'Autors',
    'Category' => 'Kategorija',
    'Category Manager' => 'Kategorijas pārvalde',
    'Category is successfully created!' => 'Kategorija ir veiksmīgi izveidota!',
    'Category is successfully deleted!' => 'Kategorija ir veiksmīgi izdzēsta!',
    'Category is successfully updated!' => 'Kategorija ir veiksmīgi atjaunota!',
    'Changed status successfully!' => 'Statuss ir veiksmīgi mainīts!',
    'Created on' => 'Izveidots',
    'Current status' => 'Pašreizējais statuss',
    'Delete Category' => 'Dzēst Kategoriju',
    'Delete Post' => 'Dzēst Rakstu',
    'Description' => 'Apraksts',
    'Details' => 'Informacija',
    'Edit Category' => 'Rediģēt kategoriju',
    'Edit Post' => 'Rediģēt rakstu',
    'Enter Category Title' => 'Ievadiet kategorijas nosaukumu',
    'Enter Finish Publishing date' => 'Ievadiet publicēšanas beigu datumu',
    'Enter Post Title' => 'Ievadiet raksta nosaukumu',
    'Enter Published date' => 'Ievadiet publicēšanas datumu',
    'Enter Start Publishing date' => 'Ievadiet publicēšanas sākuma datumu',
    'Finish Publishing' => 'Rādīt līdz',
    'Hits' => 'Apskate',
    'Id' => 'Id',
    'Information' => 'Informacija',
    'Language' => 'Valoda',
    'Last edited by' => ' Rediģēja',
    'Last edited on' => 'Rediģēts',
    'Media' => 'Media',
    'Meta' => 'Meta',
    'Meta Description' => 'Meta apraksts',
    'Meta Keywords' => 'Meta atslēgvārdi',
    'No' => 'Nē',
    'Not set' => 'Nav uzstādīts',
    'Parent' => 'Vecāks',
    'Post' => 'Raksts',
    'Post Manager' => 'Rakstu pārvalde',
    'Post is successfully created!' => 'Raksts ir veiksmīgi izveidots!',
    'Post is successfully deleted!' => 'Raksts ir veiksmīgi izdzēsts!',
    'Post is successfully updated!' => 'Raksts ir veiksmīgi atjaunots!',
    'Published' => 'Publicēts',
    'Published on' => 'Publicēts',
    'Publishing info' => 'Publicēšanas informacija',
    'Relationship' => 'Saistības',
    'Removed image successfully!' => 'Attēls ir veiksmīgi izdzēsts!',
    'Reset' => 'Dzēst',
    'Saved on' => 'Saglabāts',
    'Search' => 'Meklēšana',
    'Select a status' => 'Izvēlieties statusu',
    'Seo' => 'Seo',
    'Short description' => 'Īss apraksts',
    'Slug' => 'Draudzīgs URL',
    'Start Publishing' => 'Rādīt no',
    'Status' => 'Statuss',
    'The requested page does not exist.' => 'Pieprasītā lapa neeksistē.',
    'This slug "{value}" is already exists.' => '"{value}" URL jau ir aizņemts.',
    'Title' => 'Nosaukums',
    'View Category' => 'Apskatīt kategoriju',
    'View Post' => 'Apskatīt rakstu',
    'Yes' => 'Jā',
    'post has not been saved yet.' => 'raksts vēl nebija saglabāts',
];
