<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '- Select Post -' => 'Izvēlieties Rakstu',
    'Add new menu type' => 'Izveidot izvēlni',
    'An error has occurred ({error})' => 'Kļūda ({error})',
    'Delete Menu Type' => 'Dzēst Izvēlni',
    'Edit menu type' => 'Rediģēt izvēlni',
    'Language' => 'Valoda',
    'Menu type' => 'Izvēlne',
    'The requested page does not exist.' => 'Pieprasītā lapa neeksistē.',
    'This menutype alias "{value}" is already exists.' => 'Izvēlnes aizstājvārds "{value}" jau ir aizņemts.',
    '- First -' => '- Sākumā -',
    '- Last -' => '- Beigās -',
    '- Select Category -' => '- Izvēlieties kategoriju -',
    '- Select Page -' => '- Izvēlieties lapu -',
    '- Select Type -' => '- Izvēlieties tipu -',
    'Actions' => 'Darbības',
    'Add Menu' => 'Izveidot izvēlni',
    'Add new Menu Item' => 'Pievienot jaunu izvēlnes elementu',
    'Are you sure you want to delete this item?' => 'Vai jūs tiešām gribat dzēst šo ierakstu?',
    'Are you sure you want to delete this record?' => 'Vai jūs tiešām gribat dzēst šo ierakstu?',
    'Category' => 'Kategorija',
    'Changed status successfully!' => 'Statuss ir veiksmīgi mainīts!',
    'Close' => 'Aizvērt',
    'Current status' => 'Pašreizējais statuss',
    'Delete Menu' => 'Dzēst Izvēlni',
    'Description' => 'Apraksts',
    'Details' => 'Informacija',
    'Edit Menu Item' => 'Rediģēt izvēlnes elementu',
    'Enter Menu Title' => 'Ievadiet izvēlnes nosaukumu',
    'Id' => 'Id',
    'Information' => 'Informacija',
    'Link' => 'Saite',
    'Menu' => 'Izvēlni',
    'Menu Item Name' => 'Ievadiet izvēlnes elementa nosaukumu',
    'Menu Item Root' => 'Izvēlnes augšējais līmenis',
    'Menu Item is successfuly created!' => 'Izvēlnes elements ir veiksmīgi izveidots!',
    'Menu Item is successfuly deleted!' => 'Izvēlnes elements ir veiksmīgi izdzēsts!',
    'Menu Item is successfuly updated!' => 'Izvēlnes elements ir veiksmīgi atjaunots!',
    'Menu Location' => 'Izvēlne',
    'Menu Manager' => 'Izvēlnes elementa pārvalde',
    'Menu Type is successfuly created!' => 'Izvēlne ir veiksmīgi izveidota!',
    'Menu Type is successfuly deleted!' => 'Izvēlne ir veiksmīgi izdzēsta!',
    'Menu Type is successfuly updated!' => 'Izvēlne ir veiksmīgi atjaunota!',
    'Menu Types' => 'Izvēlnes',
    'Menu type alias' => 'Izvēlnes aizstājvārds',
    'Meta' => 'Meta',
    'Not set' => 'Nav uzstādīts',
    'Note' => 'Piezīme',
    'Ordering' => 'Secība',
    'Ordering will be available after saving' => 'Ierakstu secību būs iespējams mainīt pēc saglabāšanas',
    'Page' => 'Lapa',
    'Parent Item' => 'Vecāks Elements',
    'Post' => 'Raksts',
    'Relationship' => 'Saistības',
    'Select' => 'Izvēlieties',
    'Select a order' => 'Izvēlieties secību',
    'Select a status' => 'Izvēlieties statusu',
    'Status' => 'Statuss',
    'Title' => 'Nosaukums',
    'Type' => 'Tips',
    'URL' => 'URL',
    'Update' => 'Atjaunot',
    'View Menu Item' => 'Apskatīt izvēlnes elementu',
];
