<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'is required at least in {langTitle} {language}.' => 'необходимо заполнить хотя бы на {langTitle} {language}.',
    'Actions' => 'Действия',
    'Add new album' => 'Добавить альбом',
    'Album' => 'Альбом',
    'Album is successfully created!' => 'Альбом был успешно добавлен!',
    'Album is successfully deleted!' => 'Альбом был успешно удален!',
    'Album is successfully updated!' => 'Альбом был успешно обновлен!',
    'Are you sure you want to delete this record?' => 'Вы действительно хотите удалить эту запись?',
    'Caption' => 'Заголовок',
    'Change language' => 'Выбор языка',
    'Changed status successfully!' => 'Статус был успешно изменён!',
    'Created on' => 'Создан',
    'Current status' => 'Текущий статус',
    'Delete' => 'Удалить',
    'Description' => 'Описание',
    'Edit album' => 'Редактировать альбом',
    'Edit photos' => 'Обновить картинки',
    'Enter album name' => 'Введите название альбома ',
    'Galleries' => 'Галереи',
    'Gallery ID' => 'Id гелереи',
    'Gallery manager' => 'Менеджер галереи',
    'ID' => 'Id',
    'Image' => 'Картинка',
    'Language' => 'Язык',
    'Last edited on' => 'Последнее редактирование',
    'Meta' => 'Мета',
    'Name' => 'Название',
    'Not set' => 'Не задано',
    'Photo Extension' => 'Расширение картинки',
    'Photo ID' => 'Id картинки',
    'Photo Mime' => 'Mime картинки',
    'Photo Name' => 'Название картинки',
    'Photo Path' => 'Путь картинки',
    'Photo Size' => 'Размер картинки',
    'Photo is successfully deleted!' => 'Картинка была успешно удалена!',
    'Photo successfully reordered!' => 'Картинки успешно отсортированы!',
    'Photos' => 'Картинки',
    'Photos is successfully updated!' => 'Картинка была успешно обновлена!',
    'Position' => 'Позиция',
    'Publishing info' => 'Информация о публикации',
    'Saved on' => 'Сохранено',
    'Select a status' => 'Выберите статус',
    'Status' => 'Статус',
    'Update' => 'Обновить',
    'Update album photos' => 'Обновить картинки альбома',
    'album has not been saved yet.' => 'альбом еще не сохранен.',
    'language' => 'Язык',
    'Delete Album' => 'Удалить Альбом',
];
