<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The requested page does not exist.' => 'Pieprasītā lapa neeksistē.',
    'An error has occurred ({error})' => 'Kļūda ({error})',
    'Add new Language' => 'Pievienot jaunu valodu',
    'Changed status successfully!' => 'Statuss ir veiksmīgi mainīts!',
    'Created on' => 'Izveidots',
    'Date Format' => 'Datuma formāts',
    'Date Time Format' => 'Datuma un laika formāts',
    'Details' => 'Informacija',
    'Edit' => 'Rediģēt',
    'Edit language' => 'Rediģēt valodu',
    'Flag' => 'Karogs',
    'Id' => 'Id',
    'Information' => 'Informacija',
    'Language Manager' => 'Valodu pārvalde',
    'Language code' => 'Valodas kods',
    'Language is successfuly created!' => 'Valoda ir veiksmīgi izveidota!',
    'Language is successfuly deleted!' => 'Valoda ir veiksmīgi izdzēsta!',
    'Language is successfuly updated!' => 'Valoda ir veiksmīgi atjaunota!',
    'Last edited on' => 'Rediģēts',
    'No' => 'Nē',
    'Order' => 'Secība',
    'Published' => 'Publicēts',
    'Publishing info' => 'Publicēšanas informacija',
    'Status' => 'Statuss',
    'This language code "{value}" is already exists.' => 'Valodas kods "{value}" jau ir aizņemts.',
    'Title' => 'Nosaukums',
    'Update' => 'Atjaunot',
    'View Language' => 'Apskatīt valodu',
    'When you delete a language, all related translations in the database will be deleted. Are you sure you want to proceed?' => 'Visi saistītie ar šo valodu tulkojumi tiks dzēsti no datu bāzes. Vai esat pārliecināti, ka vēlaties turpināt?',
    'Yes' => 'Jā',
];
