<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'The requested page does not exist.' => 'Pieprasītā lapa neeksistē.',
    'An error has occurred ({error})' => 'Kļūda ({error})',
    'Account is successfully updated!' => 'Lietotājs ir veiksmīgi atjaunots!',
    'Actions' => 'Darbības',
    'Add User' => 'Pievienot jaunu lietotāju',
    'Are you sure you want to delete this user?' => 'Vai jūs tiešām gribat dzēst šo lietotāju?',
    'Auth key' => 'Auth atslēga',
    'Avatar link' => 'Avatar saite',
    'Created on' => 'Izveidots',
    'Current password' => 'Pašreizējā parole',
    'Delete User' => 'Dzēst Lietotāju',
    'Deleted' => 'Dzēsts',
    'Details' => 'Informacija',
    'Edit Profile' => 'Rediģēt Profilu',
    'Email' => 'E-pasts',
    'Id' => 'Id',
    'Language' => 'Valoda',
    'Last Visit' => 'Pēdējais apmeklējums',
    'Last edited on' => 'Rediģēts',
    'Last login ip' => 'Pēdējās pieslēgšanās IP',
    'Meta' => 'Meta',
    'Name' => 'Vārds',
    'Never login' => 'Nekad nebija pieslēgts',
    'New Password' => 'Jaunā parole',
    'Not valid current password.' => 'Jūsu pašreizējā parole nesakrīt, lūdzu mēģiniet vēlreiz.',
    'Password hash' => 'Paroles hash',
    'Password' => 'Parole',
    'Password reset token' => 'Paroles atjaunošana token',
    'Personal Options' => 'Lietotāja konta iestatījumi',
    'Publishing info' => 'Publicēšanas informacija',
    'Repeat password' => 'Atkārtojiet paroli',
    'Role' => 'Loma',
    'Saved on' => 'Saglabāts',
    'Security' => 'Security',
    'Status' => 'Statuss',
    'Surname' => 'Uzvārds',
    'This email "{value}" has already been taken.' => 'E-pasts "{value}" jau ir aizņemts.',
    'This username "{value}" has already been taken.' => 'Lietotājvārds "{value}" jau ir aizņemts.',
    'User Account is successfully deleted!' => 'Lietotājs ir veiksmīgi dzēsts!',
    'User Manager' => 'Lietotāju pārvalde',
    'User account is successfully created!' => 'Lietotājs ir veiksmīgi izveidots!',
    'User information' => 'Lietotaja informacija',
    'Username' => 'Lietotājvārds',
    'View Profile' => 'Apskatīt profilu',
    'user has not been saved yet.' => 'lietotājs vēl nebija saglabāts',
];
