<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Created on' => 'Izveidots',
    'Last edited on' => 'Rediģēts',
    'Photo Path' => '',
    'is required at least in {langTitle} {language}.' => '',
    'language' => 'valoda',
    'Actions' => 'Darbības',
    'Add new album' => 'Izveidot jaunu albumu',
    'Album' => 'Albums',
    'Album is successfully created!' => 'Albums ir veiksmīgi izveidots!',
    'Album is successfully deleted!' => 'Albums ir veiksmīgi izdzēsts!',
    'Album is successfully updated!' => 'Albums ir veiksmīgi atjaunots!',
    'Are you sure you want to delete this record?' => 'Vai jūs tiešām gribat dzēst šo ierakstu?',
    'Caption' => 'Virsraksts',
    'Change language' => 'Valoda',
    'Changed status successfully!' => 'Statuss ir veiksmīgi mainīts!',
    'Current status' => 'Pašreizējais statuss',
    'Delete' => 'Dzēst',
    'Description' => 'Apraksts',
    'Edit album' => 'Rediģēt albumu',
    'Edit photos' => 'Rediģēt bildēs',
    'Enter album name' => 'Ievadiet albuma nosaukumu',
    'Galleries' => 'Galerijas',
    'Gallery ID' => 'Galerejas Id',
    'Gallery manager' => 'Galerejas pārvalde',
    'ID' => 'Id',
    'Image' => 'Bildē',
    'Language' => 'Valoda',
    'Meta' => 'Meta',
    'Name' => 'Nosaukums',
    'Not set' => 'Nav uzstādīts',
    'Photo Extension' => 'Bildēs  paplašinājums',
    'Photo ID' => 'Bildēs Id',
    'Photo Mime' => 'Bildēs Mime',
    'Photo Name' => 'Bildēs Nosaukums',
    'Photo Size' => 'Bildēs Izmērs',
    'Photo is successfully deleted!' => 'Bildēs ir veiksmīgi izdzēstas!',
    'Photo successfully reordered!' => 'Bildē ir veiksmīgi pārkārtota!',
    'Photos' => 'Bildēs',
    'Photos is successfully updated!' => 'Bildē ir veiksmīgi atjaunota!',
    'Position' => 'Pozīcija',
    'Publishing info' => 'Publicēšanas informacija',
    'Saved on' => 'Saglabāts',
    'Select a status' => 'Izvēlieties statusu',
    'Status' => 'Statuss',
    'Update' => 'Atjaunot',
    'Update album photos' => 'Atjaunot galereju',
    'album has not been saved yet.' => 'albums vēl nebija saglabāts.',
    'Delete Album' => 'Dzēst Albumu',
];
