<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'An error has occurred ({error})' => 'Обнаружена ошибка ({error})',
    'The requested page does not exist.' => 'Запрашиваемая страница не найдена.',
    'Add new Language' => 'Добавить новый язык',
    'Changed status successfully!' => 'Статус был успешно изменён!',
    'Created on' => 'Создан',
    'Date Format' => 'Формат даты',
    'Date Time Format' => 'Формат даты (Полный)',
    'Details' => 'Информация',
    'Edit' => 'Изменить',
    'Edit language' => 'Редактировать язык',
    'Flag' => 'Флаг',
    'Id' => 'Id',
    'Information' => 'Информация',
    'Language Manager' => 'Менеджер языков',
    'Language code' => 'Код языка',
    'Language is successfuly created!' => 'Язык был успешно добавлен!',
    'Language is successfuly deleted!' => 'Язык был успешно удален!',
    'Language is successfuly updated!' => 'Язык был успешно обновлен!',
    'Last edited on' => 'Последнее редактирование',
    'No' => 'Нет',
    'Order' => 'Порядок',
    'Published' => 'Опубликовано',
    'Publishing info' => 'Информация о публикации',
    'Status' => 'Статус',
    'This language code "{value}" is already exists.' => 'Такой "{value}" код языка уже занят.',
    'Title' => 'Заголовок',
    'Update' => 'Обновить',
    'View Language' => 'Просмотр языка',
    'When you delete a language, all related translations in the database will be deleted. Are you sure you want to proceed?' => 'Если вы удалите язык все связанные таблицы и файлы также будут удалены, вы уверены?',
    'Yes' => 'Да',
];
