<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Meta Title' => 'Мета заголовок',
    'Reference' => 'Ключ ссылки',
    'Version' => 'Версия',
    'View' => 'Вид',
    '(no parent)' => '(корневая категория)',
    'Actions' => 'Действия',
    'Add' => 'Добавить',
    'Add new Category' => 'Добавить новую рубрику',
    'Add new Post' => 'Добавить новую запись',
    'An error has occurred ({error})' => 'Обнаружена ошибка ({error})',
    'Are you sure you want to delete this record?' => 'Вы действительно хотите удалить эту запись?',
    'Author' => 'Автор',
    'Category' => 'Рубрика',
    'Category Manager' => 'Менеджер рубрик',
    'Category is successfully created!' => 'Рубрика была успешно добавлена!',
    'Category is successfully deleted!' => 'Рубрика была успешно удалена!',
    'Category is successfully updated!' => 'Рубрика была успешно обновлена!',
    'Changed status successfully!' => 'Статус был успешно изменён!',
    'Created on' => 'Создан',
    'Current status' => 'Текущий статус',
    'Delete Category' => 'Удалить Рубрику',
    'Delete Post' => 'Удалить Запись',
    'Description' => 'Описание',
    'Details' => 'Информация',
    'Edit Category' => 'Изменить рубрику',
    'Edit Post' => 'Изменить запись',
    'Enter Category Title' => 'Введите название',
    'Enter Finish Publishing date' => 'Введите завершение публикации',
    'Enter Post Title' => 'Введите заголовок записи',
    'Enter Published date' => 'Введите дату публикации',
    'Enter Start Publishing date' => 'Введите начало публикации',
    'Finish Publishing' => 'Завершение публикации',
    'Hits' => 'Просмотры',
    'Id' => 'Id',
    'Information' => 'Информация',
    'Language' => 'Язык',
    'Last edited by' => 'Редактировал',
    'Last edited on' => 'Последнее редактирование',
    'Media' => 'Медиа',
    'Meta' => 'Мета',
    'Meta Description' => 'Мета описание',
    'Meta Keywords' => 'Мета слова',
    'No' => 'Нет',
    'Not set' => 'Не задано',
    'Parent' => 'Родитель',
    'Post' => 'Запись',
    'Post Manager' => 'Менеджер записей',
    'Post is successfully created!' => 'Запись была успешно добавлена!',
    'Post is successfully deleted!' => 'Запись была успешно удалена!',
    'Post is successfully updated!' => 'Запись была успешно обновлена!',
    'Published' => 'Опубликовано',
    'Published on' => 'Дата публикации',
    'Publishing info' => 'Информация о публикации',
    'Relationship' => 'Связи',
    'Removed image successfully!' => 'Картинка была успешно удалена!',
    'Reset' => 'Отмена',
    'Saved on' => 'Сохранено',
    'Search' => 'Поиск',
    'Select a status' => 'Выберите статус',
    'Seo' => 'Seo',
    'Short description' => 'Краткое описание',
    'Slug' => 'ЧПУ',
    'Start Publishing' => 'Начало публикации',
    'Status' => 'Статус',
    'The requested page does not exist.' => 'Запрашиваемая страница не найдена.',
    'This slug "{value}" is already exists.' => 'Такая "{value}" ссылка уже занята.',
    'Title' => 'Заголовок',
    'View Category' => 'Просмотр рубрики',
    'View Post' => 'Просмотр записи',
    'Yes' => 'Да',
    'post has not been saved yet.' => 'запись еще не сохранена.',
];
