<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'An error has occurred ({error})' => 'Обнаружена ошибка ({error})',
    'The requested page does not exist.' => 'Запрашиваемая страница не найдена.',
    'Account is successfully updated!' => 'Учетная запись успешно обновлена!',
    'Actions' => 'Действия',
    'Add User' => 'Добавить Пользователя',
    'Are you sure you want to delete this user?' => 'Вы действительно хотите удалить пользователя?',
    'Auth key' => 'Ключ авторизации',
    'Avatar link' => 'Аватар URL',
    'Created on' => 'Создан',
    'Current password' => 'Текущий пароль',
    'Delete User' => 'Удалить Пользователя',
    'Deleted' => 'Удалён',
    'Details' => 'Информация',
    'Edit Profile' => 'Изменить профиль',
    'Email' => 'E-mail',
    'Id' => 'Id',
    'Language' => 'Язык',
    'Last Visit' => 'Последний раз заходил',
    'Last edited on' => 'Последнее редактирование',
    'Last login ip' => 'Последний известный IP',
    'Meta' => 'Мета',
    'Name' => 'Имя',
    'Never login' => 'Никогда',
    'New Password' => 'Новый пароль',
    'Not valid current password.' => 'Текущий пароль недействителен.',
    'Password hash' => 'Хэш пароля',
    'Password reset token' => 'Токен сброса пароля',
    'Password' => 'Пароль',
    'Personal Options' => 'Персональные настройки',
    'Publishing info' => 'Информация о публикации',
    'Repeat password' => 'Повторите пароль',
    'Role' => 'Роль',
    'Saved on' => 'Сохранено',
    'Security' => 'Безопасность',
    'Status' => 'Статус',
    'Surname' => 'Фамилия',
    'This email "{value}" has already been taken.' => 'Такой "{value}" email уже занято.',
    'This username "{value}" has already been taken.' => 'Такое "{value}" имя уже занято.',
    'User Account is successfully deleted!' => 'Пользователь был успешно удалён!',
    'User Manager' => 'Менеджер пользователей',
    'User account is successfully created!' => 'Пользователь был успешно создан!',
    'User information' => 'Информация о пользователе',
    'Username' => 'Имя пользователя',
    'View Profile' => 'Просмотр профиля',
    'user has not been saved yet.' => 'пользователь еще не был сохранён.',
];
