<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '- Select Post -' => 'Выберите запись',
    'Add new menu type' => 'Создать меню',
    'An error has occurred ({error})' => 'Обнаружена ошибка ({error})',
    'Delete Menu Type' => 'Удалить Меню',
    'Edit menu type' => 'Изменить меню',
    'Language' => 'Язык',
    'Menu type' => 'Меню',
    'The requested page does not exist.' => 'Запрашиваемая страница не найдена.',
    'This menutype alias "{value}" is already exists.' => 'Такой "{value}" псевдоним меню уже занят.',
    '- First -' => '- Первый -',
    '- Last -' => '- Последний -',
    '- Select Category -' => '- Выберите рубрику -',
    '- Select Page -' => '- Выберите страницу -',
    '- Select Type -' => '- Выберите Тип -',
    'Actions' => 'Действия',
    'Add Menu' => 'Добавить меню',
    'Add new Menu Item' => 'Добавить пункт меню',
    'Are you sure you want to delete this item?' => 'Вы действительно хотите удалить этот элемент?',
    'Are you sure you want to delete this record?' => 'Вы действительно хотите удалить эту запись?',
    'Category' => 'Рубрика',
    'Changed status successfully!' => 'Статус был успешно изменён!',
    'Close' => 'Закрыть',
    'Current status' => 'Текущий статус',
    'Delete Menu' => 'Удалить Меню',
    'Description' => 'Описание',
    'Details' => 'Информация',
    'Edit Menu Item' => 'Изменить пункт меню',
    'Enter Menu Title' => 'Введите заголовок меню',
    'Id' => 'Id',
    'Information' => 'Информация',
    'Link' => 'Ссылка',
    'Menu' => 'Меню',
    'Menu Item Name' => 'Имя пункта меню',
    'Menu Item Root' => 'Корневой пункт меню',
    'Menu Item is successfuly created!' => 'Пункт меню был успешно добавлен!',
    'Menu Item is successfuly deleted!' => 'Пункт меню был успешно удален!',
    'Menu Item is successfuly updated!' => 'Пункт меню был успешно обновлен!',
    'Menu Location' => 'Меню',
    'Menu Manager' => 'Менеджер меню',
    'Menu Type is successfuly created!' => 'Меню было успешно добавлено!',
    'Menu Type is successfuly deleted!' => 'Меню было успешно удалено!',
    'Menu Type is successfuly updated!' => 'Меню было успешно обновлено!',
    'Menu Types' => 'Псевдоним Меню',
    'Menu type alias' => 'Псевдоним меню',
    'Meta' => 'Мета',
    'Not set' => 'Не задано',
    'Note' => 'Примечание',
    'Ordering' => 'Порядок',
    'Ordering will be available after saving' => 'Настройка порядка будет доступна после сохранения',
    'Page' => 'Страница',
    'Parent Item' => 'Родительский элемент',
    'Post' => 'Запись',
    'Relationship' => 'Связи',
    'Select' => 'Выбрать',
    'Select a order' => 'Укажите порядок',
    'Select a status' => 'Выберите статус',
    'Status' => 'Статус',
    'Title' => 'Заголовок',
    'Type' => 'Тип',
    'URL' => 'URL',
    'Update' => 'Обновить',
    'View Menu Item' => 'Просмотр пункта меню',
];
