<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access' => 'Доступ',
    'Quick Access' => 'Быстрый доступ',
    'Content' => 'Контент',
    'File Manager' => 'Файл Менеджер',
    'Managers' => 'Менеджеры',
    'Setup' => 'Установки',
    'Widgets' => 'Виджеты',
    'Add Category' => 'Добавить рубрику',
    'Add Page' => 'Добавить страницу',
    'Add Post' => 'Добавить запись',
    'Add User' => 'Добавить пользователя',
    'Categories' => 'Рубрики',
    'Clear Cache' => 'Очистить Кэш',
    'Dashboard' => 'Панель управления',
    'Edit My Profile' => 'Изменить профиль',
    'Gallery' => 'Галерея',
    'Hi' => 'Привет',
    'Languages' => 'Языки',
    'Logout' => 'Выйти',
    'Manage Categories' => 'Менеджер рубрик',
    'Manage Pages' => 'Менеджер страниц',
    'Manage Posts' => 'Менеджер записей',
    'Manage Users' => 'Менеджер пользователей',
    'Menu' => 'Меню',
    'Pages' => 'Страницы',
    'Posts' => 'Записи',
    'Search' => 'Поиск',
    'Settings' => 'Настройки',
    'Site' => 'Сайт',
    'Users' => 'Пользователи',
    'Visit Site' => 'Перейти на сайт',
];
