<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Access' => 'Pieejamība',
    'Quick Access' => 'Ātrā piekļuve',
    'Content' => 'Kontents',
    'File Manager' => 'Failu Pārvalde',
    'Managers' => 'Managers',
    'Setup' => 'Uzstādīšana',
    'Widgets' => 'Widgets',
    'Add Category' => 'Pievienot kategoriju',
    'Add Page' => 'Pievienot lapu',
    'Add Post' => 'Pievienot rakstu',
    'Add User' => 'Pievienot lietotāju',
    'Categories' => 'Kategorijas',
    'Clear Cache' => 'Iztīrīt Kešatmiņu',
    'Dashboard' => 'Vadības Panelis',
    'Edit My Profile' => 'Rediģēt Profilu',
    'Gallery' => 'Galerija',
    'Hi' => 'Sveiks',
    'Languages' => 'Valodas',
    'Logout' => 'Atslēgties',
    'Manage Categories' => 'Kategorijas pārvalde',
    'Manage Pages' => 'Lapu pārvalde',
    'Manage Posts' => 'Rakstu pārvalde',
    'Manage Users' => 'Lietotāju pārvalde',
    'Menu' => 'Izvēlnes',
    'Pages' => 'Lapas',
    'Posts' => 'Raksti',
    'Search' => 'Meklēšana',
    'Settings' => 'Iestatījumi',
    'Site' => 'Vietne',
    'Users' => 'Lietotāji',
    'Visit Site' => 'Apmeklēt vietni',
];
