<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Главная страница',
    'No' => 'Нет',
    'Reference' => 'Ключ ссылки',
    'Version' => 'Версия',
    'View' => 'Вид',
    'Yes' => 'Да',
    'Actions' => 'Действия',
    'Add new Page' => 'Добавить новую страницу',
    'An error has occurred ({error})' => 'Обнаружена ошибка ({error})',
    'Are you sure you want to delete this record?' => 'Вы действительно хотите удалить эту запись?',
    'Author' => 'Автор',
    'Changed status successfully!' => 'Статус был успешно изменён!',
    'Content' => 'Контент',
    'Created on' => 'Создан',
    'Current status' => 'Текущий статус',
    'Delete Page' => 'Удалить Страницу',
    'Details' => 'Информация',
    'Edit Page' => 'Изменить страницу',
    'Enter Page Title' => 'Введите заголовок страницы',
    'Hits' => 'Просмотры',
    'Id' => 'Id',
    'Information' => 'Информация',
    'Language' => 'Язык',
    'Last edited by' => 'Редактировал',
    'Last edited on' => 'Последнее редактирование',
    'Meta' => 'Мета',
    'Meta Description' => 'Мета описание',
    'Meta Keywords' => 'Мета слова',
    'Meta Title' => 'Мета заголовок',
    'Not set' => 'Не задано',
    'Page' => 'Страница',
    'Page Manager' => 'Менеджер страниц',
    'Page is successfully deleted!' => 'Страница была успешно удалена!',
    'Page is successfuly created!' => 'Страница была успешно добавлена!',
    'Page is successfuly updated!' => 'Страница была успешно обновлена!',
    'Publishing info' => 'Информация о публикации',
    'Saved on' => 'Сохранено',
    'Select a status' => 'Выберите статус',
    'Seo' => 'Seo',
    'Slug' => 'ЧПУ',
    'Status' => 'Статус',
    'The requested page does not exist.' => 'Запрашиваемая страница не найдена.',
    'This slug "{value}" is already exists.' => 'Такая "{value}" ссылка уже занята.',
    'Title' => 'Заголовок',
    'View Page' => 'Просмотр страницы',
    'page has not been saved yet.' => 'страница еще не была сохранена.',
];
