<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Home' => 'Galvena',
    'No' => 'Nē',
    'Reference' => 'Sasaistes atslēgas',
    'Version' => 'Versija',
    'View' => 'Skats',
    'Yes' => 'Jā',
    'Actions' => 'Darbības',
    'Add new Page' => 'Pievienot jaunu lapu',
    'An error has occurred ({error})' => 'Kļūda ({error})',
    'Are you sure you want to delete this record?' => 'Vai jūs tiešām gribat dzēst šo ierakstu?',
    'Author' => 'Autors',
    'Changed status successfully!' => 'Statuss ir veiksmīgi mainīts!',
    'Content' => 'Saturs',
    'Created on' => 'Izveidots',
    'Current status' => 'Pašreizējais statuss',
    'Delete Page' => 'Dzēst Lapu',
    'Details' => 'Informacija',
    'Edit Page' => 'Rediģēt lapu',
    'Enter Page Title' => 'Ievadiet lapas nosaukumu',
    'Hits' => 'Apskate',
    'Id' => 'Id',
    'Information' => 'Informacija',
    'Language' => 'Valoda',
    'Last edited by' => 'Rediģēja',
    'Last edited on' => 'Rediģēts',
    'Meta' => 'Meta',
    'Meta Description' => 'Meta apraksts',
    'Meta Keywords' => 'Meta atslēgvārdi',
    'Meta Title' => 'Meta virsraksts',
    'Not set' => 'Nav uzstādīts',
    'Page' => 'Lapa',
    'Page Manager' => 'Lapas pārvalde',
    'Page is successfully deleted!' => 'Lapa ir veiksmīgi izdzēsta!',
    'Page is successfuly created!' => 'Lapa ir veiksmīgi izveidota!',
    'Page is successfuly updated!' => 'Lapa ir veiksmīgi atjaunota!',
    'Publishing info' => 'Publicēšanas informacija',
    'Saved on' => 'Saglabāts',
    'Select a status' => 'Izvēlieties statusu',
    'Seo' => 'Seo',
    'Slug' => 'Draudzīgs URL',
    'Status' => 'Statuss',
    'The requested page does not exist.' => 'Pieprasītā lapa neeksistē.',
    'This slug "{value}" is already exists.' => '"{value}" URL jau ir aizņemts.',
    'Title' => 'Nosaukums',
    'View Page' => 'Apskatīt lapu',
    'page has not been saved yet.' => 'lapa vēl nebija saglabāta',
];
